# Generated by Django 2.2.12 on 2021-11-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('RA', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('NomeAluno', models.CharField(max_length=50, verbose_name='Nome Aluno')),
                ('Serie', models.CharField(max_length=5, verbose_name='Série')),
                ('Periodo', models.CharField(max_length=10, verbose_name='Período')),
                ('DataNasci', models.DateField(verbose_name='Data Nascimento')),
                ('Sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=2)),
                ('EmailAluno', models.CharField(max_length=40, verbose_name='Email Aluno')),
                ('SenhaAluno', models.CharField(max_length=15, null=True, verbose_name='Senha Aluno')),
                ('NomeResp', models.CharField(max_length=50, verbose_name='Nome Responsável')),
                ('GrauParent', models.CharField(max_length=5, verbose_name='Grau de Parentesco')),
                ('TelContato', models.CharField(max_length=15, verbose_name='Telefone de Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('CodEscola', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código Escola')),
                ('NomeEscola', models.CharField(max_length=50, verbose_name='Nome Escola')),
                ('Endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('Bairro', models.CharField(max_length=200)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('NumRegistro', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Número Registro Professor')),
                ('NomeProf', models.CharField(max_length=50, verbose_name='Nome Professor')),
                ('Materia', models.CharField(max_length=30, verbose_name='Matéria')),
                ('EmailProf', models.CharField(max_length=40, verbose_name='Email Professor')),
                ('SenhaProf', models.CharField(max_length=15, verbose_name='Senha Professor')),
                ('CodEscola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota_Ativ1', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Atividade 1')),
                ('Nota_P1', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prova 1')),
                ('Nota_Ativ2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Atividade 2')),
                ('Nota_P2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prova 2')),
                ('Nota_Ativ3', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Atividade 3')),
                ('Nota_P3', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prova 3')),
                ('Nota_Ativ4', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Atividade 4')),
                ('Nota_P4', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prova 4')),
                ('CodEscola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola')),
                ('NumRegistro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Professor')),
                ('RA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Alunos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alunos',
            name='CodEscola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
