# Generated by Django 2.2.12 on 2021-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='id',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='RA',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
