# Generated by Django 2.2.12 on 2021-11-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='RA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Alunos'),
        ),
    ]
