# Generated by Django 2.2.12 on 2021-11-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20211121_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='id',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='CodEscola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='RA',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notas',
            name='CodEscola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='NumRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='CodEscola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Escola'),
        ),
    ]
