# Generated by Django 2.2.12 on 2021-11-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20211127_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='SenhaAluno',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='SenhaProf',
        ),
    ]
