# Generated by Django 2.2.12 on 2021-11-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20211121_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='SenhaAluno',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='SenhaProf',
        ),
        migrations.AddField(
            model_name='alunos',
            name='Bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='Cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='Endereco',
            field=models.CharField(max_length=100, null=True, verbose_name='Endereço'),
        ),
    ]
