# Generated by Django 2.2.12 on 2021-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20211121_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='Cidade',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='Endereco',
        ),
        migrations.AddField(
            model_name='alunos',
            name='SenhaAluno',
            field=models.CharField(max_length=15, null=True, verbose_name='Senha Aluno'),
        ),
        migrations.AddField(
            model_name='professor',
            name='SenhaProf',
            field=models.CharField(default=1, max_length=15, verbose_name='Senha Professor'),
            preserve_default=False,
        ),
    ]
