# Generated by Django 2.2.12 on 2021-11-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20211121_0934'),
        ('cadastros', '0007_auto_20211121_2138'),
    ]

    operations = [
    ]
