# Generated by Django 2.2.12 on 2021-11-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataEvento', models.DateField(verbose_name='Data')),
                ('Horario', models.TimeField(verbose_name='Ínicio')),
                ('CodEscola', models.CharField(max_length=5, verbose_name='Código Escola')),
                ('Recado', models.CharField(max_length=300, verbose_name='Aviso')),
            ],
        ),
    ]
